/**
 * Язык интерфейса.
 *
 * Двери харнеса отдают данные почти нейтрально — колонки сводки приходят
 * английскими именами (`area`, `priority`, `satisfied`), — а прозу они пишут
 * по-русски: причина отказа, довод правила, объяснение пустоты. Перевести
 * ЕЁ интерфейс не может и не должен: это слова, которыми владеет проект.
 *
 * Поэтому перевод накрывает подписи интерфейса, а не содержимое набора. Там,
 * где приходит проза харнеса, она показывается как есть — на любом языке.
 */
export type Lang = "ru" | "en";

const СЛОВАРЬ: Record<string, [string, string]> = {
  // Оболочка
  "nav.pult": ["Пульт", "Console"],
  "nav.pult.note": ["что идёт и что ждёт", "running and waiting"],
  "nav.where": ["Готовность", "Readiness"],
  "nav.where.note": ["фазы и гейты", "phases and gates"],
  "nav.tasks": ["Задачи", "Tasks"],
  "nav.tasks.note": ["конвейер", "pipeline"],
  "nav.corpus": ["Корпус", "Corpus"],
  "nav.corpus.note": ["всё, что знает проект", "everything the project knows"],
  "nav.depends": ["Зависимости", "Dependencies"],
  "nav.depends.note": ["что на чём стоит", "what rests on what"],
  "nav.unknown": ["Не знаем", "Unknown"],
  "nav.unknown.note": ["пробелы", "gaps"],
  "nav.read": ["Документы", "Documents"],
  "nav.read.note": ["читать", "read"],

  // Пульт
  "pu.working": ["Делают агенты", "Agents at work"],
  "pu.asks": ["От тебя ждут", "Waiting on you"],
  "pu.moved": ["Что поехало", "What shifted"],
  "pu.asks.note": ["без ответа конвейер стоит", "the pipeline stalls without an answer"],
  "pu.moved.note": ["стояли на том, что правили после них", "they rest on things edited later"],
  "pu.idle": ["Никто не занят: очередь задач пуста либо прогоны завершены.",
              "Nobody is busy: the task queue is empty or the runs have finished."],
  "pu.noasks": ["Ничего не ждут.", "Nothing is waiting."],
  "pu.noasks.why": ["Вопросов владельцу не отдано — конвейер идёт сам.",
                    "No questions are addressed to the owner — the pipeline runs on its own."],
  "pu.nomoved": ["Ничего не поехало.", "Nothing shifted."],
  "pu.nomoved.why": ["Ни одна запись не стоит на том, что изменили позже.",
                     "No record rests on anything edited after it."],
  "pu.answer": ["Ответить", "Answer"],
  "pu.collapse": ["Свернуть", "Collapse"],
  "pu.write": ["Записать ответ", "Save answer"],
  "pu.writing": ["Пишу…", "Saving…"],
  "pu.draft": ["Ответ владельца — он попадёт в вопрос и закроет ступень",
               "The owner's answer — it goes into the question and clears the step"],
  "pu.viaDoor": ["запись идёт дверью харнеса, как и всё прочее",
                 "written through a harness door, like everything else"],
  "pu.refused": ["дверь не приняла ответ", "the door refused the answer"],
  "pu.chain": ["вся цепочка →", "full chain →"],
  "pu.more": ["ещё", "another"],
  "pu.passed": ["пройдено", "passed"],
  "pu.of": ["из", "of"],
  "pu.gate": ["гейт", "gate"],
  "pu.red": ["красен", "failing"],
  "pu.green": ["зелен", "passing"],
  "pu.step": ["ступень", "step"],
  "pu.doing": ["делает", "doing"],
  "pu.attempt": ["попытка", "attempt"],
  "pu.reading": ["Читаю пульт…", "Reading the console…"],

  // Работа
  "wk.reading": ["Читаю работу…", "Reading work…"],
  "wk.closed": ["Закрыто", "Closed"],
  "wk.queue": ["в очереди предполёта", "in the preflight queue"],
  "wk.fresh": ["свежих", "fresh"],
  "wk.stale": ["протухших", "stale"],
  "wk.never": ["ни разу", "never run"],
  "wk.waves": ["Волны предполёта", "Preflight waves"],
  "wk.waveNote": ["доля свежих вердиктов в волне; щелчок оставляет только её",
                  "share of fresh verdicts per wave; click to keep only it"],
  "wk.honest": ["У задачи датирован только предполёт: закрытие помечено коммитом, а не датой — путь задачи лента показать не может.",
                "Only the preflight is dated: a closing is marked by a commit, not a date — the task's path is not something this timeline can show."],
  "wk.tasks": ["Задачи", "Tasks"],
  "wk.allWaves": ["все волны", "all waves"],
  "wk.none": ["В очереди пусто.", "The queue is empty."],
  "wk.colTask": ["задача", "task"],
  "wk.colTitle": ["название", "title"],
  "wk.colWhy": ["почему в очереди", "why queued"],
  "wk.colRev": ["правка", "revision"],
  "wk.ofUnclosed": ["из", "of"],
  "wk.unclosed": ["незакрытых", "unclosed"],
  "wk.reasons": ["Причины разложены дверью:", "The door breaks the reasons down:"],
  "wk.clickDrawer": ["Щелчок раскрывает задачу дровером, список остаётся.",
                     "A click opens the task in a drawer; the list stays put."],
  "wk.tornFoot": ["Красная грань и знак ↯ — ступень через голову:",
                  "A red edge and ↯ mark a step taken over the head:"],
  "wk.onWhole": ["на весь проект", "across the whole project"],
  "wk.allSame": ["Все одного рода: миновала", "All of one kind: skipped"],
  "wk.allIn": ["Все в", "All in"],
  "wk.noneTorn": ["Ни одна задача не проходила ступень через голову.",
                  "No task took a step over the head."],
  "wk.movedOut": ["Ступени без задач вынесены вправо; в лестнице они стоят так:",
                  "Steps with no tasks are moved to the right; in the ladder they sit like this:"],
  "wk.nth": ["-я", "th"],
  "wk.unusedHead": ["ступени без задач:", "steps with no tasks:"],
  "wk.empty": ["пусто", "empty"],
  "wk.stepsCount": ["этапов", "milestones"],
  "wk.stepsPick": ["щелчок уводит на доску с этим отбором", "a click opens the board filtered to it"],
  "im.head": ["Последствия правки", "What an edit touches"],
  "im.reopens": ["переоткроет", "reopens"],
  "im.touched": ["затронет", "touches"],
  "im.depth": ["глубина", "depth"],
  "im.none": ["На этой записи не стоит ничего: править её безопасно.",
              "Nothing stands on this record: editing it is safe."],
  "im.willReopen": ["переоткроется", "will reopen"],
  "im.step": ["шаг", "step"],
  "li.head": ["Объявленные связи", "Declared links"],
  "li.none": ["Наборы связей для этого рода не объявлены — сказать нечего, а не «связей нет».",
              "No link sets are declared for this kind — that is «nothing to say», not «no links»."],
  "li.empty": ["Объявленные наборы пусты: связей не записано ни одной.",
               "The declared sets are empty: not a single link is recorded."],
  "im.reading": ["Считаю последствия…", "Computing consequences…"],
  // Ход субагента. Слова приходят от сервера ключами; подпись — наша.
  "run.provisioning": ["готовит место", "provisioning"],
  "run.running": ["работает", "running"],
  "run.review": ["на ревью", "in review"],
  "run.blocked": ["встал", "blocked"],
  "run.failed": ["упал", "failed"],
  // Состояния гейта.
  "gate.passed": ["пройден", "passed"],
  "gate.failed": ["провален", "failed"],
  "gate.unknown": ["мерить нечем", "nothing to measure by"],
  "gate.waived": ["снят с этого проекта", "waived for this project"],
  // ── Готовность ──────────────────────────────────────────────────────────
  "rd.reading": ["Считаю готовность…", "Measuring readiness…"],
  "rd.head": ["Готовность", "Readiness"],
  "rd.sub": ["чему верить · где стоим · что держит · что не прошло",
             "what to trust · where we stand · what holds · what did not pass"],
  "rd.of": ["из", "of"],
  "rd.violations": ["нарушений", "violations"],
  "rd.all": ["Все", "All"],
  "rd.here": ["здесь", "here"],
  "rd.holdsNow": ["держит сейчас", "holding now"],
  "rd.run": ["запустить", "run"],
  "rd.failedHead": ["Что не прошло", "What did not pass"],
  "rd.allPhases": ["все фазы", "all phases"],
  "rd.allPassed": ["Здесь всё пройдено.", "Everything here has passed."],
  "rd.bySubject": ["Счёт по предметам", "Counted by subject"],
  "rd.pipeline": ["Конвейер задач", "Task pipeline"],
  "rd.neverFell": ["не роняли", "never fell"],
  "rd.written": ["Что записано:", "What is recorded:"],
  "rd.noFindings": ["Находок нет.", "No findings."],
  "rd.exKey": ["ключ исключения", "exception key"],
  "rd.declare": ["объявить:", "declare:"],
  "rd.ladder": ["Лестница входа", "Entry ladder"],
  "rd.noItems": ["пунктов нет", "no items"],
  // ── Пульт ───────────────────────────────────────────────────────────────
  "pu.agents": ["Делают агенты", "Agents are working"],
  "pu.waiting": ["От тебя ждут", "Waiting on you"],
  "pu.waitingNote": ["без ответа конвейер стоит", "without an answer the pipeline stops"],
  "pu.noneWaiting": ["Ничего не ждут.", "Nothing is waiting."],
  "pu.noneWaitingWhy": ["Вопросов владельцу не отдано — конвейер идёт сам.",
                        "No question has been handed to the owner — the pipeline runs on its own."],
  "pu.byDoor": ["запись идёт дверью харнеса, как и всё прочее",
                "the write goes through a harness door, like everything else"],
  "pu.movedNote": ["стояли на том, что правили после них",
                   "stood on something edited after them"],
  "pu.noneMoved": ["Ничего не поехало.", "Nothing moved."],
  "pu.noneMovedWhy": ["Ни одна запись не стоит на том, что изменили позже.",
                      "No record stands on anything changed later."],
  "pu.whole": ["вся цепочка →", "the whole chain →"],
  "pu.answerHint": ["Ответ владельца — он попадёт в вопрос и закроет ступень",
                    "The owner's answer — it goes into the question and closes the step"],
  // ── Не знаем ────────────────────────────────────────────────────────────
  "un.reading": ["Собираю неизвестное…", "Collecting the unknown…"],
  "un.owner": ["владелец", "owner"],
  "un.items": ["пунктов", "items"],
  "un.noMethod": ["без способа", "without a method"],
  "un.owners": ["владельцев", "owners"],
  "un.saidWhere": ["где сказано", "where it is said"],
  "un.about": ["про что", "about what"],
  "un.claimed": ["заявлено", "claimed"],
  "un.seeReadiness": ["Эти пункты видны в «Готовности» — там же их состояние и причина.",
                      "These items appear under Readiness — with their state and reason."],
  "un.head": ["Чего мы не знаем", "What we do not know"],
  "un.sub": ["не «нет», а «нечем ответить» — это разные вещи",
             "not «no» but «nothing to answer with» — these differ"],
  "un.noMethodFull": ["без способа проверки", "without a way to check"],
  "un.emptyIsFact": ["Пустой ответ — факт.", "An empty answer is a fact."],
  "un.gapNotFact": ["Отсутствие способа — не факт, а пробел",
                    "A missing method is not a fact but a gap"],
  "un.none": ["Незакрытых пробелов нет: у каждого пункта есть способ проверки.",
              "No open gaps: every item has a way to check it."],
  "un.closedBy": ["закрывается", "closed by"],
  // ── Документы ───────────────────────────────────────────────────────────
  "rr.readingKinds": ["Читаю виды…", "Reading kinds…"],
  "rr.head": ["Документы", "Documents"],
  "rr.sub": ["вид · сущность · что написано", "kind · entity · what is written"],
  "rr.readingNames": ["Читаю имена…", "Reading names…"],
  "rr.unreadable": ["Не читается:", "Cannot read:"],
  "rr.pickLeft": ["Выберите сущность слева.", "Pick an entity on the left."],
  "rr.readingToc": ["Читаю оглавление…", "Reading the table of contents…"],
  "rr.openAll": ["раскрыть всё", "open all"],
  "rr.again": ["ещё раз", "again"],
  "rr.sectionUnread": ["Раздел не прочитался.", "The section did not load."],
  "rr.noOwnText": ["Собственного текста нет — только подразделы ниже.",
                   "No text of its own — only the subsections below."],
  "rr.reading": ["Читаю…", "Reading…"],
  "rr.writtenIn": ["записано в", "written in"],
  "rr.kinds": ["Виды", "Kinds"],
  "rr.searchName": ["искать по имени…", "search by name…"],
  "rr.searchNameAria": ["Поиск по имени", "Search by name"],
  // ── Где мы ──────────────────────────────────────────────────────────────
  "wh.noServer": ["Сервер не отвечает:", "The server does not answer:"],
  "wh.reading": ["Смотрю, где мы…", "Looking at where we stand…"],
  "wh.head": ["Где мы", "Where we stand"],
  "wh.sub": ["первая невыполненная ступень, и что она держит",
             "the first unmet step, and what it holds"],
  "wh.recount": ["· набор изменился, пересчёт идёт", "· the corpus changed, recounting"],
  "wh.step": ["ступень", "step"],
  "wh.run": ["запустить", "run"],
  "wh.why": ["почему", "why"],
  "wh.holds": ["держит", "holds"],
  "wh.side": ["сторона", "side"],
  "wh.none": ["Невыполненных ступеней нет.", "There are no unmet steps."],
  "wh.done": ["Пройдено", "Passed"],
  "wh.skipped": ["· пропущено с причиной", "· skipped with a reason"],
  "wh.unknown": ["чего мы не знаем", "what we do not know"],
  "wh.unknownNote": ["пунктов и статусов без способа проверки",
                     "items and statuses with no way to check them"],
  // ── Сводка ──────────────────────────────────────────────────────────────
  "tg.reading": ["Читаю проекты…", "Reading projects…"],
  "tg.counting": ["Считаю гейты обоих…", "Measuring both gates…"],
  "tg.head": ["Сводка", "Overview"],
  "tg.sub": ["все проекты разом · где они разошлись при одной мерке",
             "all projects at once · where they diverge under one measure"],
  "tg.agreed": ["пунктов · сошлось", "items · agreed"],
  "tg.open": ["открыть →", "open →"],
  "tg.diverged": ["Где разошлись", "Where they diverged"],
  "tg.divergedNote": ["пункты общие · разница объяснима состоянием, а не меркой",
                      "the items are shared · the difference is in state, not in the measure"],
  "tg.divergedLow": ["где разошлись", "where they diverged"],
  "tg.allItems": ["все пункты", "all items"],
  "tg.gate": ["Гейт", "Gate"],
  "tg.item": ["Пункт", "Item"],
  "tg.no": ["нет", "no"],
  "tg.notHere": ["пункта у этого проекта нет", "this project has no such item"],
  // ── Зависимости ─────────────────────────────────────────────────────────
  "dp.reading": ["Читаю связи…", "Reading links…"],
  "dp.kinds": ["Роды", "Kinds"],
  "dp.willReopen": ["Что переоткроется", "What will reopen"],
  "dp.pickKind": ["Выберите род на карте.", "Pick a kind on the map."],
  "dp.on": ["На", "On"],
  "dp.pickRecord": ["— выберите запись —", "— pick a record —"],
  "dp.touched": ["затронуто", "touched"],
  "dp.nobody": ["На этой записи не стоит никто: правка никого не затронет.",
                "Nothing stands on this record: an edit touches nobody."],
  // ── Палитра ─────────────────────────────────────────────────────────────
  "pl.pick": ["↑↓ выбрать", "↑↓ pick"],
  "pl.open": ["↵ открыть", "↵ open"],
  "pl.esc": ["esc закрыть", "esc close"],
  "pl.searching": ["ищу…", "searching…"],
  "pl.head": ["Палитра", "Palette"],
  "pl.call": ["Искать", "Search"],
  // Отказ без слов двери: сказать за неё нечего, но и молчать нельзя.
  "er.noNet": ["Сервер не ответил — сети нет или он не запущен.",
               "The server did not answer — no network, or it is not running."],
  "er.silent": ["Дверь отказала и не объяснила почему.",
                "The door refused and did not say why."],
  "wk.mirror": ["зеркало проверок", "check mirror"],
  "rr.pointsTo": ["Ведёт на", "Points to"],
  "rr.pointsNone": ["Ни на что не ссылается.", "Points to nothing."],
  "pl.hint": ["раздел или имя сущности — ADR-0138, Q-372, M0-T12…",
              "a section or an entity name — ADR-0138, Q-372, M0-T12…"],
  "pl.what": ["Что открыть", "What to open"],
  // ── Цепочка, строки, дровер, фазы, проекты ─────────────────────────────
  "ch.none": ["Требований нет — цепочку строить не из чего.",
              "No requirements — there is nothing to build a chain from."],
  "ch.whole": ["не рвётся", "unbroken"],
  "ch.wholeSay": ["цепочка целая", "the chain is whole"],
  "ch.missing": ["не хватает звена", "a link is missing"],
  "ch.orphan": ["не связаны ни с чем", "linked to nothing"],
  "ch.show": ["показать эти требования", "show these requirements"],
  "rw.search": ["искать ·", "search ·"],
  "rw.walk": ["ходить ·", "walk ·"],
  "rw.open": ["открыть", "open"],
  "rw.byNumber": ["искать по номеру и по смыслу…", "search by number and by meaning…"],
  "rw.searchAria": ["Поиск", "Search"],
  "dr.reading": ["Читаю документ…", "Reading the document…"],
  "dr.noDoc": ["Документа нет — только объявленные поля.",
               "No document — only the declared fields."],
  "dr.close": ["Закрыть", "Close"],
  "ph.reading": ["Читаю фазы…", "Reading phases…"],
  "ph.tasks": ["задачи", "tasks"],
  "ph.noCount": ["своего счёта нет", "no count of its own"],
  "ph.noGate": ["гейта нет", "no gate"],
  "pj.all": ["все проекты", "all projects"],
  "pj.summary": ["сводка", "overview"],
  "pj.pick": ["Выбрать проект", "Pick a project"],
  "pj.head": ["Проекты", "Projects"],
  "pj.readingList": ["читаю список", "reading the list"],
  "lv.ask": ["спросить сервер сейчас", "ask the server now"],
  "ap.screens": ["Экраны", "Screens"],
  "ap.namedProject": ["В ссылке назван проект", "The link names project"],
  "ap.namedPage": ["В ссылке назван раздел", "The link names section"],
  "rd.itemsPassed": ["пунктов прошли", "items passed"],
  "rr.single": ["одиночка", "singleton"],
  "lv.ago": ["назад", "ago"],
  "lv.sec": ["сек", "s"],
  "lv.min": ["мин", "min"],
  "lv.hour": ["ч", "h"],
  "lv.now": ["только что", "just now"],
  "lv.never": ["ещё не читали", "not read yet"],
  "nav.open": ["Открыть разделы", "Open sections"],
  "nav.close": ["Закрыть разделы", "Close sections"],
  "nav.all": ["Все проекты", "All projects"],
  "wk.viewList": ["список", "list"],
  "wk.viewBoard": ["доска", "board"],
  "wk.viewSteps": ["этапы", "milestones"],
  "wk.devTasks": ["задач разработки", "dev tasks"],
  "wk.mirrors": ["зеркал проверок", "check mirrors"],
  "wk.torn": ["со ступенью через голову", "skipped a step"],
  "wk.at": ["стоит", "here"],
  "wk.unmeasured": ["неизмеримо", "unmeasurable"],
  "wk.noFact": ["факт этой ступени никто не записывает — это «неизвестно», а не «пусто».",
                "nobody records this step's fact — that is «unknown», not «empty»."],
  "wk.transient": ["ненакопительная ступень: факт описывает состояние сейчас, и его отсутствие не значит, что задача здесь не была.",
                   "a non-accumulating step: the fact describes the state right now, and its absence does not mean the task was never here."],
  "wk.passed": ["дальше прошли все", "everyone went further"],
  "wk.missed": ["миновала", "skipped"],
  "wk.boardNote": ["каждая задача стоит в самой дальней ступени, которой достигла; красная грань — ступень через голову",
                   "each task sits at the furthest step it reached; a red edge means a step was skipped"],
  "wk.stepsNote": ["полоса этапа — доля его задач по ступеням",
                   "a milestone's bar is the share of its tasks by step"],
  "wk.mirrorOf": ["зеркало", "mirror"],
  "wk.more": ["ещё", "more"],
  "wk.idle": ["не начата", "not started"],
  "wk.freshOne": ["свеж", "fresh"],
  "wk.staleOne": ["протух", "stale"],
  "wk.neverOne": ["ни разу", "never"],

  // Корпус
  "co.reading": ["Читаю корпус…", "Reading the corpus…"],
  "co.kinds": ["Роды", "Kinds"],
  "co.rows": ["записей", "records"],
  "co.pick": ["Выберите род слева.", "Pick a kind on the left."],
  "co.none": ["Записей этого рода нет.", "There are no records of this kind."],
  "co.back": ["← ко всем", "← all records"],
  "co.proof": ["Чем доказано", "Proven by"],
  "co.rests": ["На нём стоят", "Rests on it"],
  "co.written": ["Где написано", "Written in"],
  "co.impact": ["Правка затронет", "An edit touches"],
  "co.willReopen": ["переоткроются", "will reopen"],
  "co.linked": ["связано", "linked"],
  "co.section": ["раздел", "section"],
  "co.noproof": ["нечем", "nothing"],
  "co.live.current": ["свежо", "current"],
  "co.live.reopened": ["переоткрыто", "reopened"],
  "co.search": ["Искать по имени", "Search by name"],
  "co.cols": ["колонок", "more columns"],
  "co.fold": ["свернуть колонки", "fold columns"],
  "co.groupBy": ["собрать по", "group by"],

  // Зависимости
  "de.skeleton": ["Скелет", "Skeleton"],
  "de.kinds": ["Роды", "Kinds"],
  "de.what": ["Что переоткроется", "What will reopen"],
  "de.reading": ["Читаю связи…", "Reading the links…"],
  "de.rule": ["значит «А стоит на Б»: правка Б переоткрывает А. Толщина — сколько связей.",
              "means “A rests on B”: editing B reopens A. Thickness is the number of links."],
  "de.pickKind": ["Выберите род на карте.", "Pick a kind on the map."],
  "de.pickRow": ["— выберите запись —", "— pick a record —"],
  "de.on": ["стоят:", "rest on it:"],
  "de.nobody": ["никто — правка не переоткроет ничего", "nobody — an edit reopens nothing"],
  "de.touched": ["затронуто", "touched"],
  "de.ofThem": ["из них переоткроется", "of those will reopen"],
  "de.step": ["шаг", "step"],
  "de.willReopen": ["переоткроется", "will reopen"],
  "de.linked": ["связано", "linked"],
  "de.noOne": ["На этой записи не стоит никто: правка никого не затронет.",
               "Nothing rests on this record: an edit touches nobody."],
  "de.reopens": ["Переоткрываются при правке связей:", "Reopen when their links change:"],
  "de.noReopens": ["ни один", "none"],
  "de.notReopen": ["не переоткрывается", "does not reopen"],
  "de.reopened": ["переоткрыто", "reopened"],
  "de.byDomain": ["по областям", "by domain"],
  "de.byKind": ["по родам", "by kind"],
};

/** Названия родов. Имя вида — слово проекта; перевод лишь подписывает его. */
const РОДЫ: Record<string, [string, string]> = {
  requirement: ["требование", "requirement"],
  check: ["проверка", "check"],
  story: ["история", "story"],
  task: ["задача", "task"],
  "red-task": ["красная задача", "red task"],
  milestone: ["этап", "milestone"],
  question: ["вопрос", "question"],
  screen: ["экран", "screen"],
  need: ["потребность", "need"],
  decision: ["решение", "decision"],
  rationale: ["рассуждение", "rationale"],
  "lint-rule": ["правило кода", "lint rule"],
  assertion: ["утверждение", "assertion"],
  term: ["термин", "term"],
  article: ["статья", "article"],
  feature: ["фича", "feature"],
  version: ["выпуск", "release"],
  run: ["прогон", "run"],
  risk: ["риск", "risk"],
  gate: ["гейт", "gate"],
};

/** Области проекта. Имя области — слово проекта; перевод его подписывает. */
const ОБЛАСТИ: Record<string, string> = {
  "требования": "requirements",
  "доказательство": "proof",
  "план": "plan",
  "знание": "knowledge",
  "надзор": "oversight",
};

const КЛЮЧ = "mh-lang";

export function langNow(): Lang {
  const url = new URL(window.location.href).searchParams.get("lang");
  if (url === "en" || url === "ru") return url;
  try {
    const kept = localStorage.getItem(КЛЮЧ);
    if (kept === "en" || kept === "ru") return kept;
  } catch {
    // Хранилище бывает закрыто — язык тогда просто не запоминается.
  }
  return "ru";
}

export function setLang(l: Lang): void {
  try {
    localStorage.setItem(КЛЮЧ, l);
  } catch {
    // см. выше
  }
  const url = new URL(window.location.href);
  url.searchParams.set("lang", l);
  window.history.replaceState({}, "", url);
  window.dispatchEvent(new Event("mh-lang"));
}

/**
 * Подпись по ключу. Ключа нет — возвращается сам ключ: пропущенный перевод
 * ВИДЕН, а не подменён пустотой. Молчание здесь читалось бы как «так и надо».
 */
export function say(l: Lang, key: string): string {
  const пара = СЛОВАРЬ[key];
  if (!пара) return key;
  return l === "en" ? пара[1] : пара[0];
}

/** Как зовут область. Необъявленная показывается своим именем. */
export function domainName(l: Lang, d: string): string {
  return l === "en" ? (ОБЛАСТИ[d] ?? d) : d;
}

/** Как зовут род на этом языке. Неизвестный род показывается своим именем. */
export function kindName(l: Lang, kind: string): string {
  const пара = РОДЫ[kind];
  if (!пара) return kind;
  return l === "en" ? пара[1] : пара[0];
}
